name: App
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          working-directory: internal

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: task app:build
