name: App
on:
    push:
        branches:
            - main
        tags:
            - v*
    pull_request:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Check out code
              uses: actions/checkout@v3

            - name: Lint code
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19

            - name: Install Task
              uses: arduino/setup-task@v1

            - name: Check out code
              uses: actions/checkout@v3

            - name: Build
              run: task build
